/*
 * Offline reciter downloads — APP ONLY.
 *
 * Downloads a reciter's full per-surah engine assets (114 surah MP3s + 114
 * timings JSONs, from gs://m7mdiyat-tafsir-data) into the Cache API so the
 * surah audio engine (src/surahAudio.js) can play that reciter with no
 * connection. Mirrors the verified-put + retry + online-retry pattern of the
 * Tafsir offline channel (src/app.js), adapted for a multi-reciter selection.
 *
 * Two responsibilities:
 *   1. Download / delete / track per-reciter (pub/sub consumed by
 *      src/offline-panel.js — the "القرّاء" section).
 *   2. Install cache-first hooks on surahAudio so DOWNLOADED reciters play from
 *      the cache (online too — the user opted for "always prefer downloaded
 *      audio"); a cache miss falls back to network, so nothing regresses for
 *      reciters that were never downloaded.
 *
 * Pulled in (statically) by offline-panel.js, and initialised from app.js
 * init() behind isApp(); the website bundle never loads this module.
 *
 * Per-reciter size truth is the bundled public/reciter-audio-sizes.json
 * (generated by scripts/measure-reciter-sizes.mjs) — small, ships in the app,
 * available offline, so the live total is instant + accurate.
 */

"use strict";

import { isApp } from "./app.js";
import { surahAudio, audioUrl, timingsUrl } from "./surahAudio.js";

/* Bump on any change to the cached asset SET *or its bytes* so existing app
 * users re-download the corrected files; old caches are reclaimed by
 * purgeStaleReciterCaches(). v2: audio re-encoded to mono 64 kbps (~half the
 * size, same timing alignment). The cache name AND ready key move together —
 * bumping only the cache would leave the ready map reporting "downloaded" while
 * the new cache is empty, which would break offline playback. Bumping the ready
 * key surfaces those reciters as not-downloaded so the smaller files re-fetch,
 * and listing the old cache in STALE_RECITER_CACHES frees the user's storage. */
const RECITER_CACHE_NAME = "reciter-audio-v2";
const RECITER_READY_KEY = "m7_reciter_offline_v2";
const STALE_RECITER_CACHES = ["reciter-audio-v1"];
const SIZES_URL = "/reciter-audio-sizes.json";
const SURAH_COUNT = 114;
const CONCURRENCY = 3; // multi-MB (some 100MB+) bodies — keep peak memory sane
const OFFLINE_MESSAGE = "لا يوجد اتصال بالإنترنت — سيستأنف عند عودة الاتصال";

const DL_MESSAGES = [
  "جارٍ تحميل التلاوة",
  "نُجهّز صوت القارئ لك",
  "تلاوة كاملة بين يديك قريبًا",
  "جارٍ حفظ السور على جهازك",
];
const DL_FINAL = "جاهز! استمع بدون إنترنت";

/* Injected registry (single source of truth lives in app.js RECITERS). */
let RECITERS = {};
let RECITER_ORDER = [];

/* ------------------------------------------------------------ Cache handle */
let _cachePromise = null;
function reciterCache() {
  if (!_cachePromise) _cachePromise = caches.open(RECITER_CACHE_NAME);
  return _cachePromise;
}

/* ------------------------------------------------------------ Ready map */
// localStorage JSON: { [reciterId]: 1 } — set ONLY after a verified full download.
function readReadyMap() {
  if (!isApp()) return {};
  try { return JSON.parse(localStorage.getItem(RECITER_READY_KEY) || "{}") || {}; }
  catch { return {}; }
}
function writeReadyMap(map) {
  try { localStorage.setItem(RECITER_READY_KEY, JSON.stringify(map)); } catch { }
}
function markReady(id, ready) {
  const map = readReadyMap();
  if (ready) map[id] = 1; else delete map[id];
  writeReadyMap(map);
}
export function isReciterReady(id) {
  if (!isApp()) return false;
  return readReadyMap()[id] === 1;
}
/* Used by the playback routing in app.js / mushaf.js: a downloaded reciter is
 * routed through the surah engine (which is cache-first) in every mode. */
export function isReciterOfflineReady(id) { return isReciterReady(id); }

/* ------------------------------------------------------------ URLs for a reciter */
function reciterUrls(id) {
  const urls = [];
  for (let s = 1; s <= SURAH_COUNT; s++) {
    urls.push(audioUrl(id, s));
    urls.push(timingsUrl(id, s));
  }
  return urls;
}

/* ------------------------------------------------------------ Size manifest */
let _sizes = null;        // { reciters: { id: { total, audio, timings } } }
let _sizesPromise = null;
export function loadReciterSizes() {
  if (_sizes) return Promise.resolve(_sizes);
  if (!_sizesPromise) {
    _sizesPromise = fetch(SIZES_URL)
      .then((r) => (r.ok ? r.json() : null))
      .then((j) => { _sizes = j || { reciters: {} }; return _sizes; })
      .catch(() => { _sizes = { reciters: {} }; return _sizes; });
  }
  return _sizesPromise;
}
export function reciterSizeBytes(id) {
  return _sizes?.reciters?.[id]?.total || 0;
}

/* ------------------------------------------------------------ Reciter list */
export function getReciterList() {
  return RECITER_ORDER
    .filter((id) => RECITERS[id])
    .map((id) => ({ id, name: RECITERS[id].name, bytes: reciterSizeBytes(id) }));
}

/* ============================================================ Pub/sub state
 * RECITER_STATE[id] = { status, pct, done, total, message }
 * status: idle | queued | downloading | done | offline | error
 * A subscriber gets the WHOLE map on every change (ready reciters surface as
 * { status: "done" } even if untouched this session). */
const RECITER_STATE = {};
const LISTENERS = new Set();

function snapshot() {
  const out = {};
  for (const { id } of getReciterList()) {
    if (isReciterReady(id)) out[id] = { status: "done" };
    else out[id] = RECITER_STATE[id] ? { ...RECITER_STATE[id] } : { status: "idle" };
  }
  return out;
}
function emit() {
  const snap = snapshot();
  for (const fn of LISTENERS) { try { fn(snap); } catch { } }
}
function setReciterState(id, patch) {
  RECITER_STATE[id] = { ...(RECITER_STATE[id] || { status: "idle", pct: 0, done: 0, total: 0, message: "" }), ...patch };
  emit();
}
export function subscribeReciterDl(fn) {
  LISTENERS.add(fn);
  try { fn(snapshot()); } catch { }
  return () => LISTENERS.delete(fn);
}
/* True while any reciter is queued/downloading (panel locks selection). */
export function isReciterDownloadBusy() {
  return Object.values(RECITER_STATE).some((s) => s.status === "downloading" || s.status === "queued");
}

/* ------------------------------------------------------------ Verified put */
// Download one file and confirm it actually landed in the cache. Returns true
// only when the body is re-readable (mirrors cacheTafsirFile in app.js — never
// trust res.ok alone; cache.put can throw on quota and must be re-verified).
async function cacheOne(cache, url) {
  try {
    const res = await fetch(url, { cache: "reload" });
    if (!res.ok) return false;
    await cache.put(url, res);
    return !!(await cache.match(url));
  } catch {
    return false;
  }
}
async function missingFor(cache, urls) {
  const missing = [];
  for (const u of urls) {
    try { if (!(await cache.match(u))) missing.push(u); }
    catch { missing.push(u); }
  }
  return missing;
}

/* ------------------------------------------------------------ Download */
let DL_INFLIGHT = null;
let ONLINE_ARMED = false;
let _pendingSelection = [];   // reciters still wanted when an online-retry fires

function armOnlineRetry() {
  if (ONLINE_ARMED) return;
  ONLINE_ARMED = true;
  const onOnline = () => {
    window.removeEventListener("online", onOnline);
    ONLINE_ARMED = false;
    if (_pendingSelection.length) downloadReciters(_pendingSelection.slice());
  };
  window.addEventListener("online", onOnline);
}

/* Download every selected reciter that isn't already ready, one reciter at a
 * time (bounds peak memory and gives clear per-reciter progress). */
export function downloadReciters(ids) {
  if (DL_INFLIGHT) return DL_INFLIGHT;
  if (!isApp() || typeof caches === "undefined") return Promise.resolve({ ok: false });

  const wanted = (ids || []).filter((id) => RECITERS[id] && !isReciterReady(id));
  _pendingSelection = wanted.slice();
  if (!wanted.length) return Promise.resolve({ ok: true });

  if (!navigator.onLine) {
    for (const id of wanted) setReciterState(id, { status: "offline", message: OFFLINE_MESSAGE });
    armOnlineRetry();
    return Promise.resolve({ ok: false, offline: true });
  }

  // Mark the rest of the selection as queued up front (immediate UI feedback).
  for (const id of wanted) setReciterState(id, { status: "queued", message: "بالانتظار" });

  DL_INFLIGHT = (async () => {
    // Durable storage so a multi-GB cache isn't evicted under pressure.
    try { await navigator.storage?.persist?.(); } catch { }
    const cache = await reciterCache();
    let allOk = true;

    for (const id of wanted) {
      if (isReciterReady(id)) continue; // a parallel/retry pass already finished it

      const urls = reciterUrls(id);
      const total = urls.length;
      let done = 0;
      setReciterState(id, { status: "downloading", pct: 0, done, total, message: DL_MESSAGES[0] });

      let msgIdx = 0;
      const rotation = setInterval(() => {
        msgIdx = (msgIdx + 1) % DL_MESSAGES.length;
        setReciterState(id, { message: DL_MESSAGES[msgIdx] });
      }, 2500);

      async function pass(batch, countProgress) {
        const queue = batch.slice();
        const failures = [];
        async function worker() {
          while (queue.length) {
            const url = queue.shift();
            const ok = await cacheOne(cache, url);
            if (!ok) failures.push(url);
            if (countProgress) {
              done++;
              setReciterState(id, { done, total, pct: Math.round((done / total) * 100) });
            }
          }
        }
        await Promise.all(Array.from({ length: CONCURRENCY }, worker));
        return failures;
      }

      let failures = await pass(urls, true);
      for (let attempt = 0; attempt < 2 && failures.length; attempt++) {
        failures = await pass(failures, false);
      }
      const missing = failures.length ? failures : await missingFor(cache, urls);
      clearInterval(rotation);

      if (missing.length === 0) {
        markReady(id, true);
        setReciterState(id, { status: "done", pct: 100, message: DL_FINAL });
        _pendingSelection = _pendingSelection.filter((x) => x !== id);
      } else {
        allOk = false;
        markReady(id, false);
        if (!navigator.onLine) {
          // Connection dropped mid-batch: mark this + the rest offline, retry on `online`.
          setReciterState(id, { status: "offline", message: OFFLINE_MESSAGE });
          for (const rest of wanted) {
            if (!isReciterReady(rest) && rest !== id) setReciterState(rest, { status: "offline", message: OFFLINE_MESSAGE });
          }
          armOnlineRetry();
          return { ok: false, offline: true };
        }
        console.warn("[reciter-offline] not ready — files missing:", id, missing.length);
        setReciterState(id, { status: "error", message: "تعذّر تحميل بعض الملفات" });
        // Keep going with the other selected reciters.
      }
    }
    return { ok: allOk };
  })().finally(() => { DL_INFLIGHT = null; });
  return DL_INFLIGHT;
}

/* ------------------------------------------------------------ Delete */
export async function deleteReciter(id) {
  markReady(id, false);
  try {
    const cache = await reciterCache();
    // Cache API can't delete by prefix — remove each known URL for this reciter.
    for (const url of reciterUrls(id)) {
      try { await cache.delete(url); } catch { }
    }
  } catch { }
  setReciterState(id, { status: "idle", pct: 0, done: 0, total: 0, message: "" });
  return { ok: true };
}

/* ------------------------------------------------------------ Stale purge */
export async function purgeStaleReciterCaches() {
  if (!isApp() || typeof caches === "undefined") return;
  for (const name of STALE_RECITER_CACHES) { try { await caches.delete(name); } catch { } }
}

/* ============================================================ Offline hooks */
function installOfflineAudioHooks() {
  surahAudio.setOfflineHooks({
    // SYNC gate — only downloaded reciters take the async cached-blob branch.
    isDownloaded: (reciter) => isReciterReady(reciter),
    // Cache → blob: URL for the MP3, or null to fall back to the network URL.
    resolveAudioUrl: async (reciter, surah) => {
      if (!isApp() || typeof caches === "undefined") return null;
      try {
        const cache = await reciterCache();
        const hit = await cache.match(audioUrl(reciter, surah));
        if (!hit) return null;
        const blob = await hit.blob();
        return URL.createObjectURL(blob);
      } catch { return null; }
    },
    revokeAudioUrl: (url) => { try { URL.revokeObjectURL(url); } catch { } },
    // Cached timings Response, or null to fall back to the network fetch.
    fetchTimings: async (url) => {
      if (!isApp() || typeof caches === "undefined") return null;
      try {
        const cache = await reciterCache();
        return (await cache.match(url)) || null;
      } catch { return null; }
    },
  });
}

/* ------------------------------------------------------------ Init */
export function initReciterOffline(deps) {
  RECITERS = deps?.reciters || {};
  RECITER_ORDER = deps?.reciterOrder || Object.keys(RECITERS);
  installOfflineAudioHooks();
  // Warm the size manifest so the panel's first open shows totals instantly.
  loadReciterSizes();
  purgeStaleReciterCaches();
}
